modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Mercuri/NoHotbarSwap/issues"
license = "MIT"

[[mods]]
modId = "nohotbarswap"
version = "${version}"
displayName = "No Hotbar Swap"
authors = "Mercuri"
description = '''
Prevent accidental hotbar swapping when pressing number keys in inventory!
'''
logoFile = "assets/nohotbarswap/icon.png"

[[dependencies.nohotbarswap]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nohotbarswap]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "CLIENT"
